version: "3.9"

services:
  iqas:
    build: .
    ports: ["8000:8000"]
    env_file: .env               # ← ADD
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 2s
      retries: 10
    depends_on:
      - minio

  minio:                          # ← NEW
    image: minio/minio:RELEASE.2024-06-04T19-20-08Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # S3
      - "9001:9001"   # Console UI

volumes:
  minio_data:
