version: "3.9"

services:
  iqas:
    build: .
    ports:
      - "8000:8000"
    volumes:            # hot-reload inside the container while you code
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
